# Generated by Django 2.2 on 2020-05-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('deadline', models.DateTimeField(blank=True)),
                ('performed', models.BooleanField(default=False)),
            ],
        ),
    ]
